library(dplyr)
housing=read.csv("Quiz3_Q1_Data.csv")
housing<-mutate(housing,agricultureLogical=factor(1*(ACR==3 & AGS==6),labels=c("false","true")))
which(agricultureLogical=="True")
housing.f<-filter(housing,agricultureLogical=="true")
housing.f

install.packages("jpeg")
library(jpeg)
picture=readJPEG("Quiz3_Q2", native=TRUE)
quantile(picture,.3)

columnheaders<-c("CountryCode","Ranking","skipCol","Economy","GDP","skip2","skip3","skip4","skip5","skip6")
columnClasses<-c("factor","numeric","NULL","factor","factor","NULL","NULL","NULL","NULL","NULL")
edu<-read.csv("Quiz3_Q3_Edu")
gdp<-read.csv("Quiz3_Q3_GDP",skip=5,nrows=190,header = FALSE, sep = ",", col.names = columnheaders, colClasses =columnClasses)
head(gdp)
head(edu)
mergedData<-inner_join(gdp,edu,by="CountryCode")
head(mergedData)
nrow(mergedData)
sorted<-arrange(mergedData,desc(Ranking))
sorted
grouped<-group_by(mergedData,Income.Group)
summarize(grouped,mean(Ranking))

install.packages("Hmisc")
library(Hmisc)
mergedData$RankGroups <- cut2(mergedData$Rank, g=5)
table(mergedData$RankGroups, mergedData$`Income Group`)
